### ISSUE TITLE
Trigger

### ISSUE THREAD

**Issue by runsy** [rubenwardy/sfinv#4]
There are to methods for pages (tabs)
- get
- on_enter

I want to trigger a function.
1) If I use 'get' and 'on_enter', both are triggered when the formspec arises and when the tab is selected too.
2) But if the formspec is reopened with that tab active, the tab is shown at first sight, but no trigger at all.

So the bug is:
1) What is the diference between both events, refered to this issue?
2) ´on_enter´ or ´get´ should be triggered when the formspec is reopened with that tab active.

**Comment by rubenwardy** [comment]
On enter is when the tab is selected. Get is when the formspec is generation. A tab may be generated multiple times without changing tabs and calling on enter

**Comment by runsy** [comment]
Ruben think on a refresh function (actually set_page).

bye.
